name: Build zig master for Debian

on:
  workflow_dispatch:
    inputs:
      zig_version:
        description: The version of zig to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-zig:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout zig-debian
        uses: actions/checkout@v6

      - name: Build zig Debian
        run: ./build_zig_debian.sh ${{ inputs.zig_version }} ${{ inputs.build_version }}

      - name: Build zig Ubuntu
        run: ./build_zig_ubuntu.sh ${{ inputs.zig_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact
          path: zig-master_*.deb


  release-zig:
    name: Release zig for Debian
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build-zig
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          name: artifact

      - name: Publish Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: zig-master_*.deb
          name: Zig ${{ inputs.zig_version }}+${{ inputs.build_version }}
          tag_name: ${{ inputs.zig_version }}-${{ inputs.build_version }}
          fail_on_unmatched_files: true
          
