name: Build zig master for Debian

on:
  workflow_dispatch:
    inputs:
      zig_version:
        description: "The version of zig to build (e.g., 0.14.0-dev.1911+2146d9006)"
        type: string
        required: true
      build_version:
        description: "The build version (e.g., 1)"
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-zig:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zig-debian
        uses: actions/checkout@v6

      - name: Build zig
        run: ./build_zig_debian.sh ${{ inputs.zig_version }} ${{ inputs.build_version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: debian-packages
          path: "*.deb"

  release-zig:
    name: Release zig for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-zig
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: debian-packages

      - name: Publish Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: false
          draft: false
          make_latest: true
          files: "*.deb"
          name: "Zig ${{ inputs.zig_version }} (Build ${{ inputs.build_version }})"
          tag_name: "${{ inputs.zig_version }}-${{ inputs.build_version }}"
